/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R500RouteImport } from './routes/500'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistsIdRouteImport } from './routes/therapists.$id'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.$role'
import { Route as DashboardRoleRouteImport } from './routes/dashboard.$role'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as CheckoutBookingIdRouteImport } from './routes/checkout.$bookingId'
import { Route as BookTherapistIdRouteImport } from './routes/book.$therapistId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthRoleRouteImport } from './routes/auth.role'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthActionRouteImport } from './routes/auth.action'
import { Route as DashboardRoleIndexRouteImport } from './routes/dashboard.$role.index'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'
import { Route as DashboardAdminSessionsRouteImport } from './routes/dashboard.admin.sessions'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/dashboard.admin.payments'
import { Route as DashboardAdminContentRouteImport } from './routes/dashboard.admin.content'
import { Route as DashboardAdminAnalyticsRouteImport } from './routes/dashboard.admin.analytics'
import { Route as DashboardAdminAiLogsRouteImport } from './routes/dashboard.admin.ai-logs'
import { Route as DashboardRoleVibeRouteImport } from './routes/dashboard.$role.vibe'
import { Route as DashboardRoleSessionsRouteImport } from './routes/dashboard.$role.sessions'
import { Route as DashboardRoleReportsRouteImport } from './routes/dashboard.$role.reports'
import { Route as DashboardRoleProfileRouteImport } from './routes/dashboard.$role.profile'
import { Route as DashboardRolePendingRouteImport } from './routes/dashboard.$role.pending'
import { Route as DashboardRoleNotificationsRouteImport } from './routes/dashboard.$role.notifications'
import { Route as DashboardRoleMoodRouteImport } from './routes/dashboard.$role.mood'
import { Route as DashboardRoleInstapayRouteImport } from './routes/dashboard.$role.instapay'
import { Route as DashboardRoleFindRouteImport } from './routes/dashboard.$role.find'
import { Route as DashboardRoleChildrenRouteImport } from './routes/dashboard.$role.children'
import { Route as DashboardRoleChatRouteImport } from './routes/dashboard.$role.chat'
import { Route as DashboardRoleBookingsRouteImport } from './routes/dashboard.$role.bookings'
import { Route as DashboardRoleAvailabilityRouteImport } from './routes/dashboard.$role.availability'
import { Route as DashboardRoleApprovalsRouteImport } from './routes/dashboard.$role.approvals'
import { Route as DashboardRoleAchievementsRouteImport } from './routes/dashboard.$role.achievements'
import { Route as ApiReportsCreateRouteImport } from './routes/api/reports/create'
import { Route as ApiPolarWebhookRouteImport } from './routes/api/polar/webhook'
import { Route as ApiPolarCheckoutRouteImport } from './routes/api/polar/checkout'
import { Route as ApiInstapayProofRouteImport } from './routes/api/instapay/proof'
import { Route as ApiBookingLockRouteImport } from './routes/api/booking/lock'
import { Route as ApiBookingCancelRouteImport } from './routes/api/booking/cancel'
import { Route as ApiAiTranscribeRouteImport } from './routes/api/ai/transcribe'
import { Route as ApiAiSummarizeRouteImport } from './routes/api/ai/summarize'
import { Route as ApiAiIntakeRouteImport } from './routes/api/ai/intake'
import { Route as ApiAiCrisisCheckRouteImport } from './routes/api/ai/crisis-check'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAdminApproveTherapistRouteImport } from './routes/api/admin/approve-therapist'
import { Route as DashboardRoleSessionsIdRouteImport } from './routes/dashboard.$role.sessions.$id'
import { Route as ApiSessionsIdTokenRouteImport } from './routes/api/sessions.$id.token'
import { Route as ApiSessionsIdEndRouteImport } from './routes/api/sessions.$id.end'
import { Route as ApiAdminUsersStatusRouteImport } from './routes/api/admin/users.status'
import { Route as ApiAdminInstapayVerifyRouteImport } from './routes/api/admin/instapay.verify'

const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsIdRoute = TherapistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TherapistsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/$role',
  path: '/onboarding/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/dashboard/$role',
  path: '/dashboard/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutBookingIdRoute = CheckoutBookingIdRouteImport.update({
  id: '/checkout/$bookingId',
  path: '/checkout/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTherapistIdRoute = BookTherapistIdRouteImport.update({
  id: '/book/$therapistId',
  path: '/book/$therapistId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthActionRoute = AuthActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardRoleIndexRoute = DashboardRoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/dashboard/admin/users',
  path: '/dashboard/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/dashboard/admin/settings',
  path: '/dashboard/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminSessionsRoute = DashboardAdminSessionsRouteImport.update({
  id: '/dashboard/admin/sessions',
  path: '/dashboard/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/dashboard/admin/payments',
  path: '/dashboard/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminContentRoute = DashboardAdminContentRouteImport.update({
  id: '/dashboard/admin/content',
  path: '/dashboard/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminAnalyticsRoute = DashboardAdminAnalyticsRouteImport.update({
  id: '/dashboard/admin/analytics',
  path: '/dashboard/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminAiLogsRoute = DashboardAdminAiLogsRouteImport.update({
  id: '/dashboard/admin/ai-logs',
  path: '/dashboard/admin/ai-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleVibeRoute = DashboardRoleVibeRouteImport.update({
  id: '/vibe',
  path: '/vibe',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleSessionsRoute = DashboardRoleSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleReportsRoute = DashboardRoleReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleProfileRoute = DashboardRoleProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRolePendingRoute = DashboardRolePendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleNotificationsRoute =
  DashboardRoleNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardRoleRoute,
  } as any)
const DashboardRoleMoodRoute = DashboardRoleMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleInstapayRoute = DashboardRoleInstapayRouteImport.update({
  id: '/instapay',
  path: '/instapay',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleFindRoute = DashboardRoleFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleChildrenRoute = DashboardRoleChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleChatRoute = DashboardRoleChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleBookingsRoute = DashboardRoleBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleAvailabilityRoute =
  DashboardRoleAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => DashboardRoleRoute,
  } as any)
const DashboardRoleApprovalsRoute = DashboardRoleApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoleRoute,
} as any)
const DashboardRoleAchievementsRoute =
  DashboardRoleAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => DashboardRoleRoute,
  } as any)
const ApiReportsCreateRoute = ApiReportsCreateRouteImport.update({
  id: '/api/reports/create',
  path: '/api/reports/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarWebhookRoute = ApiPolarWebhookRouteImport.update({
  id: '/api/polar/webhook',
  path: '/api/polar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarCheckoutRoute = ApiPolarCheckoutRouteImport.update({
  id: '/api/polar/checkout',
  path: '/api/polar/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstapayProofRoute = ApiInstapayProofRouteImport.update({
  id: '/api/instapay/proof',
  path: '/api/instapay/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingLockRoute = ApiBookingLockRouteImport.update({
  id: '/api/booking/lock',
  path: '/api/booking/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingCancelRoute = ApiBookingCancelRouteImport.update({
  id: '/api/booking/cancel',
  path: '/api/booking/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTranscribeRoute = ApiAiTranscribeRouteImport.update({
  id: '/api/ai/transcribe',
  path: '/api/ai/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSummarizeRoute = ApiAiSummarizeRouteImport.update({
  id: '/api/ai/summarize',
  path: '/api/ai/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiIntakeRoute = ApiAiIntakeRouteImport.update({
  id: '/api/ai/intake',
  path: '/api/ai/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCrisisCheckRoute = ApiAiCrisisCheckRouteImport.update({
  id: '/api/ai/crisis-check',
  path: '/api/ai/crisis-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApproveTherapistRoute =
  ApiAdminApproveTherapistRouteImport.update({
    id: '/api/admin/approve-therapist',
    path: '/api/admin/approve-therapist',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardRoleSessionsIdRoute = DashboardRoleSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardRoleSessionsRoute,
} as any)
const ApiSessionsIdTokenRoute = ApiSessionsIdTokenRouteImport.update({
  id: '/api/sessions/$id/token',
  path: '/api/sessions/$id/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIdEndRoute = ApiSessionsIdEndRouteImport.update({
  id: '/api/sessions/$id/end',
  path: '/api/sessions/$id/end',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersStatusRoute = ApiAdminUsersStatusRouteImport.update({
  id: '/api/admin/users/status',
  path: '/api/admin/users/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInstapayVerifyRoute = ApiAdminInstapayVerifyRouteImport.update({
  id: '/api/admin/instapay/verify',
  path: '/api/admin/instapay/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/auth/action': typeof AuthActionRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$therapistId': typeof BookTherapistIdRoute
  '/checkout/$bookingId': typeof CheckoutBookingIdRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/$role': typeof DashboardRoleRouteWithChildren
  '/onboarding/$role': typeof OnboardingRoleRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/api/admin/approve-therapist': typeof ApiAdminApproveTherapistRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/crisis-check': typeof ApiAiCrisisCheckRoute
  '/api/ai/intake': typeof ApiAiIntakeRoute
  '/api/ai/summarize': typeof ApiAiSummarizeRoute
  '/api/ai/transcribe': typeof ApiAiTranscribeRoute
  '/api/booking/cancel': typeof ApiBookingCancelRoute
  '/api/booking/lock': typeof ApiBookingLockRoute
  '/api/instapay/proof': typeof ApiInstapayProofRoute
  '/api/polar/checkout': typeof ApiPolarCheckoutRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/reports/create': typeof ApiReportsCreateRoute
  '/dashboard/$role/achievements': typeof DashboardRoleAchievementsRoute
  '/dashboard/$role/approvals': typeof DashboardRoleApprovalsRoute
  '/dashboard/$role/availability': typeof DashboardRoleAvailabilityRoute
  '/dashboard/$role/bookings': typeof DashboardRoleBookingsRoute
  '/dashboard/$role/chat': typeof DashboardRoleChatRoute
  '/dashboard/$role/children': typeof DashboardRoleChildrenRoute
  '/dashboard/$role/find': typeof DashboardRoleFindRoute
  '/dashboard/$role/instapay': typeof DashboardRoleInstapayRoute
  '/dashboard/$role/mood': typeof DashboardRoleMoodRoute
  '/dashboard/$role/notifications': typeof DashboardRoleNotificationsRoute
  '/dashboard/$role/pending': typeof DashboardRolePendingRoute
  '/dashboard/$role/profile': typeof DashboardRoleProfileRoute
  '/dashboard/$role/reports': typeof DashboardRoleReportsRoute
  '/dashboard/$role/sessions': typeof DashboardRoleSessionsRouteWithChildren
  '/dashboard/$role/vibe': typeof DashboardRoleVibeRoute
  '/dashboard/admin/ai-logs': typeof DashboardAdminAiLogsRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/content': typeof DashboardAdminContentRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/$role/': typeof DashboardRoleIndexRoute
  '/api/admin/instapay/verify': typeof ApiAdminInstapayVerifyRoute
  '/api/admin/users/status': typeof ApiAdminUsersStatusRoute
  '/api/sessions/$id/end': typeof ApiSessionsIdEndRoute
  '/api/sessions/$id/token': typeof ApiSessionsIdTokenRoute
  '/dashboard/$role/sessions/$id': typeof DashboardRoleSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/auth/action': typeof AuthActionRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$therapistId': typeof BookTherapistIdRoute
  '/checkout/$bookingId': typeof CheckoutBookingIdRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/onboarding/$role': typeof OnboardingRoleRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/api/admin/approve-therapist': typeof ApiAdminApproveTherapistRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/crisis-check': typeof ApiAiCrisisCheckRoute
  '/api/ai/intake': typeof ApiAiIntakeRoute
  '/api/ai/summarize': typeof ApiAiSummarizeRoute
  '/api/ai/transcribe': typeof ApiAiTranscribeRoute
  '/api/booking/cancel': typeof ApiBookingCancelRoute
  '/api/booking/lock': typeof ApiBookingLockRoute
  '/api/instapay/proof': typeof ApiInstapayProofRoute
  '/api/polar/checkout': typeof ApiPolarCheckoutRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/reports/create': typeof ApiReportsCreateRoute
  '/dashboard/$role/achievements': typeof DashboardRoleAchievementsRoute
  '/dashboard/$role/approvals': typeof DashboardRoleApprovalsRoute
  '/dashboard/$role/availability': typeof DashboardRoleAvailabilityRoute
  '/dashboard/$role/bookings': typeof DashboardRoleBookingsRoute
  '/dashboard/$role/chat': typeof DashboardRoleChatRoute
  '/dashboard/$role/children': typeof DashboardRoleChildrenRoute
  '/dashboard/$role/find': typeof DashboardRoleFindRoute
  '/dashboard/$role/instapay': typeof DashboardRoleInstapayRoute
  '/dashboard/$role/mood': typeof DashboardRoleMoodRoute
  '/dashboard/$role/notifications': typeof DashboardRoleNotificationsRoute
  '/dashboard/$role/pending': typeof DashboardRolePendingRoute
  '/dashboard/$role/profile': typeof DashboardRoleProfileRoute
  '/dashboard/$role/reports': typeof DashboardRoleReportsRoute
  '/dashboard/$role/sessions': typeof DashboardRoleSessionsRouteWithChildren
  '/dashboard/$role/vibe': typeof DashboardRoleVibeRoute
  '/dashboard/admin/ai-logs': typeof DashboardAdminAiLogsRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/content': typeof DashboardAdminContentRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/$role': typeof DashboardRoleIndexRoute
  '/api/admin/instapay/verify': typeof ApiAdminInstapayVerifyRoute
  '/api/admin/users/status': typeof ApiAdminUsersStatusRoute
  '/api/sessions/$id/end': typeof ApiSessionsIdEndRoute
  '/api/sessions/$id/token': typeof ApiSessionsIdTokenRoute
  '/dashboard/$role/sessions/$id': typeof DashboardRoleSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/auth/action': typeof AuthActionRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$therapistId': typeof BookTherapistIdRoute
  '/checkout/$bookingId': typeof CheckoutBookingIdRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/$role': typeof DashboardRoleRouteWithChildren
  '/onboarding/$role': typeof OnboardingRoleRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/api/admin/approve-therapist': typeof ApiAdminApproveTherapistRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/crisis-check': typeof ApiAiCrisisCheckRoute
  '/api/ai/intake': typeof ApiAiIntakeRoute
  '/api/ai/summarize': typeof ApiAiSummarizeRoute
  '/api/ai/transcribe': typeof ApiAiTranscribeRoute
  '/api/booking/cancel': typeof ApiBookingCancelRoute
  '/api/booking/lock': typeof ApiBookingLockRoute
  '/api/instapay/proof': typeof ApiInstapayProofRoute
  '/api/polar/checkout': typeof ApiPolarCheckoutRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/reports/create': typeof ApiReportsCreateRoute
  '/dashboard/$role/achievements': typeof DashboardRoleAchievementsRoute
  '/dashboard/$role/approvals': typeof DashboardRoleApprovalsRoute
  '/dashboard/$role/availability': typeof DashboardRoleAvailabilityRoute
  '/dashboard/$role/bookings': typeof DashboardRoleBookingsRoute
  '/dashboard/$role/chat': typeof DashboardRoleChatRoute
  '/dashboard/$role/children': typeof DashboardRoleChildrenRoute
  '/dashboard/$role/find': typeof DashboardRoleFindRoute
  '/dashboard/$role/instapay': typeof DashboardRoleInstapayRoute
  '/dashboard/$role/mood': typeof DashboardRoleMoodRoute
  '/dashboard/$role/notifications': typeof DashboardRoleNotificationsRoute
  '/dashboard/$role/pending': typeof DashboardRolePendingRoute
  '/dashboard/$role/profile': typeof DashboardRoleProfileRoute
  '/dashboard/$role/reports': typeof DashboardRoleReportsRoute
  '/dashboard/$role/sessions': typeof DashboardRoleSessionsRouteWithChildren
  '/dashboard/$role/vibe': typeof DashboardRoleVibeRoute
  '/dashboard/admin/ai-logs': typeof DashboardAdminAiLogsRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/content': typeof DashboardAdminContentRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/$role/': typeof DashboardRoleIndexRoute
  '/api/admin/instapay/verify': typeof ApiAdminInstapayVerifyRoute
  '/api/admin/users/status': typeof ApiAdminUsersStatusRoute
  '/api/sessions/$id/end': typeof ApiSessionsIdEndRoute
  '/api/sessions/$id/token': typeof ApiSessionsIdTokenRoute
  '/dashboard/$role/sessions/$id': typeof DashboardRoleSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/500'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/therapists'
    | '/auth/action'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/role'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/book/$therapistId'
    | '/checkout/$bookingId'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/dashboard/$role'
    | '/onboarding/$role'
    | '/settings/security'
    | '/therapists/$id'
    | '/api/admin/approve-therapist'
    | '/api/ai/chat'
    | '/api/ai/crisis-check'
    | '/api/ai/intake'
    | '/api/ai/summarize'
    | '/api/ai/transcribe'
    | '/api/booking/cancel'
    | '/api/booking/lock'
    | '/api/instapay/proof'
    | '/api/polar/checkout'
    | '/api/polar/webhook'
    | '/api/reports/create'
    | '/dashboard/$role/achievements'
    | '/dashboard/$role/approvals'
    | '/dashboard/$role/availability'
    | '/dashboard/$role/bookings'
    | '/dashboard/$role/chat'
    | '/dashboard/$role/children'
    | '/dashboard/$role/find'
    | '/dashboard/$role/instapay'
    | '/dashboard/$role/mood'
    | '/dashboard/$role/notifications'
    | '/dashboard/$role/pending'
    | '/dashboard/$role/profile'
    | '/dashboard/$role/reports'
    | '/dashboard/$role/sessions'
    | '/dashboard/$role/vibe'
    | '/dashboard/admin/ai-logs'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/content'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/$role/'
    | '/api/admin/instapay/verify'
    | '/api/admin/users/status'
    | '/api/sessions/$id/end'
    | '/api/sessions/$id/token'
    | '/dashboard/$role/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/500'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/therapists'
    | '/auth/action'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/role'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/book/$therapistId'
    | '/checkout/$bookingId'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/onboarding/$role'
    | '/settings/security'
    | '/therapists/$id'
    | '/api/admin/approve-therapist'
    | '/api/ai/chat'
    | '/api/ai/crisis-check'
    | '/api/ai/intake'
    | '/api/ai/summarize'
    | '/api/ai/transcribe'
    | '/api/booking/cancel'
    | '/api/booking/lock'
    | '/api/instapay/proof'
    | '/api/polar/checkout'
    | '/api/polar/webhook'
    | '/api/reports/create'
    | '/dashboard/$role/achievements'
    | '/dashboard/$role/approvals'
    | '/dashboard/$role/availability'
    | '/dashboard/$role/bookings'
    | '/dashboard/$role/chat'
    | '/dashboard/$role/children'
    | '/dashboard/$role/find'
    | '/dashboard/$role/instapay'
    | '/dashboard/$role/mood'
    | '/dashboard/$role/notifications'
    | '/dashboard/$role/pending'
    | '/dashboard/$role/profile'
    | '/dashboard/$role/reports'
    | '/dashboard/$role/sessions'
    | '/dashboard/$role/vibe'
    | '/dashboard/admin/ai-logs'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/content'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/$role'
    | '/api/admin/instapay/verify'
    | '/api/admin/users/status'
    | '/api/sessions/$id/end'
    | '/api/sessions/$id/token'
    | '/dashboard/$role/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/500'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/therapists'
    | '/auth/action'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/role'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/book/$therapistId'
    | '/checkout/$bookingId'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/dashboard/$role'
    | '/onboarding/$role'
    | '/settings/security'
    | '/therapists/$id'
    | '/api/admin/approve-therapist'
    | '/api/ai/chat'
    | '/api/ai/crisis-check'
    | '/api/ai/intake'
    | '/api/ai/summarize'
    | '/api/ai/transcribe'
    | '/api/booking/cancel'
    | '/api/booking/lock'
    | '/api/instapay/proof'
    | '/api/polar/checkout'
    | '/api/polar/webhook'
    | '/api/reports/create'
    | '/dashboard/$role/achievements'
    | '/dashboard/$role/approvals'
    | '/dashboard/$role/availability'
    | '/dashboard/$role/bookings'
    | '/dashboard/$role/chat'
    | '/dashboard/$role/children'
    | '/dashboard/$role/find'
    | '/dashboard/$role/instapay'
    | '/dashboard/$role/mood'
    | '/dashboard/$role/notifications'
    | '/dashboard/$role/pending'
    | '/dashboard/$role/profile'
    | '/dashboard/$role/reports'
    | '/dashboard/$role/sessions'
    | '/dashboard/$role/vibe'
    | '/dashboard/admin/ai-logs'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/content'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/$role/'
    | '/api/admin/instapay/verify'
    | '/api/admin/users/status'
    | '/api/sessions/$id/end'
    | '/api/sessions/$id/token'
    | '/dashboard/$role/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R500Route: typeof R500Route
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TherapistsRoute: typeof TherapistsRouteWithChildren
  BookTherapistIdRoute: typeof BookTherapistIdRoute
  CheckoutBookingIdRoute: typeof CheckoutBookingIdRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  DashboardRoleRoute: typeof DashboardRoleRouteWithChildren
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  ApiAdminApproveTherapistRoute: typeof ApiAdminApproveTherapistRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiCrisisCheckRoute: typeof ApiAiCrisisCheckRoute
  ApiAiIntakeRoute: typeof ApiAiIntakeRoute
  ApiAiSummarizeRoute: typeof ApiAiSummarizeRoute
  ApiAiTranscribeRoute: typeof ApiAiTranscribeRoute
  ApiBookingCancelRoute: typeof ApiBookingCancelRoute
  ApiBookingLockRoute: typeof ApiBookingLockRoute
  ApiInstapayProofRoute: typeof ApiInstapayProofRoute
  ApiPolarCheckoutRoute: typeof ApiPolarCheckoutRoute
  ApiPolarWebhookRoute: typeof ApiPolarWebhookRoute
  ApiReportsCreateRoute: typeof ApiReportsCreateRoute
  DashboardAdminAiLogsRoute: typeof DashboardAdminAiLogsRoute
  DashboardAdminAnalyticsRoute: typeof DashboardAdminAnalyticsRoute
  DashboardAdminContentRoute: typeof DashboardAdminContentRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
  DashboardAdminSessionsRoute: typeof DashboardAdminSessionsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  ApiAdminInstapayVerifyRoute: typeof ApiAdminInstapayVerifyRoute
  ApiAdminUsersStatusRoute: typeof ApiAdminUsersStatusRoute
  ApiSessionsIdEndRoute: typeof ApiSessionsIdEndRoute
  ApiSessionsIdTokenRoute: typeof ApiSessionsIdTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists/$id': {
      id: '/therapists/$id'
      path: '/$id'
      fullPath: '/therapists/$id'
      preLoaderRoute: typeof TherapistsIdRouteImport
      parentRoute: typeof TherapistsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$role': {
      id: '/onboarding/$role'
      path: '/onboarding/$role'
      fullPath: '/onboarding/$role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role': {
      id: '/dashboard/$role'
      path: '/dashboard/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$bookingId': {
      id: '/checkout/$bookingId'
      path: '/checkout/$bookingId'
      fullPath: '/checkout/$bookingId'
      preLoaderRoute: typeof CheckoutBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$therapistId': {
      id: '/book/$therapistId'
      path: '/book/$therapistId'
      fullPath: '/book/$therapistId'
      preLoaderRoute: typeof BookTherapistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/role': {
      id: '/auth/role'
      path: '/role'
      fullPath: '/auth/role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/action': {
      id: '/auth/action'
      path: '/action'
      fullPath: '/auth/action'
      preLoaderRoute: typeof AuthActionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/$role/': {
      id: '/dashboard/$role/'
      path: '/'
      fullPath: '/dashboard/$role/'
      preLoaderRoute: typeof DashboardRoleIndexRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/dashboard/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/dashboard/admin/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/sessions': {
      id: '/dashboard/admin/sessions'
      path: '/dashboard/admin/sessions'
      fullPath: '/dashboard/admin/sessions'
      preLoaderRoute: typeof DashboardAdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/payments': {
      id: '/dashboard/admin/payments'
      path: '/dashboard/admin/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/content': {
      id: '/dashboard/admin/content'
      path: '/dashboard/admin/content'
      fullPath: '/dashboard/admin/content'
      preLoaderRoute: typeof DashboardAdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/analytics': {
      id: '/dashboard/admin/analytics'
      path: '/dashboard/admin/analytics'
      fullPath: '/dashboard/admin/analytics'
      preLoaderRoute: typeof DashboardAdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/ai-logs': {
      id: '/dashboard/admin/ai-logs'
      path: '/dashboard/admin/ai-logs'
      fullPath: '/dashboard/admin/ai-logs'
      preLoaderRoute: typeof DashboardAdminAiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role/vibe': {
      id: '/dashboard/$role/vibe'
      path: '/vibe'
      fullPath: '/dashboard/$role/vibe'
      preLoaderRoute: typeof DashboardRoleVibeRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/sessions': {
      id: '/dashboard/$role/sessions'
      path: '/sessions'
      fullPath: '/dashboard/$role/sessions'
      preLoaderRoute: typeof DashboardRoleSessionsRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/reports': {
      id: '/dashboard/$role/reports'
      path: '/reports'
      fullPath: '/dashboard/$role/reports'
      preLoaderRoute: typeof DashboardRoleReportsRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/profile': {
      id: '/dashboard/$role/profile'
      path: '/profile'
      fullPath: '/dashboard/$role/profile'
      preLoaderRoute: typeof DashboardRoleProfileRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/pending': {
      id: '/dashboard/$role/pending'
      path: '/pending'
      fullPath: '/dashboard/$role/pending'
      preLoaderRoute: typeof DashboardRolePendingRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/notifications': {
      id: '/dashboard/$role/notifications'
      path: '/notifications'
      fullPath: '/dashboard/$role/notifications'
      preLoaderRoute: typeof DashboardRoleNotificationsRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/mood': {
      id: '/dashboard/$role/mood'
      path: '/mood'
      fullPath: '/dashboard/$role/mood'
      preLoaderRoute: typeof DashboardRoleMoodRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/instapay': {
      id: '/dashboard/$role/instapay'
      path: '/instapay'
      fullPath: '/dashboard/$role/instapay'
      preLoaderRoute: typeof DashboardRoleInstapayRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/find': {
      id: '/dashboard/$role/find'
      path: '/find'
      fullPath: '/dashboard/$role/find'
      preLoaderRoute: typeof DashboardRoleFindRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/children': {
      id: '/dashboard/$role/children'
      path: '/children'
      fullPath: '/dashboard/$role/children'
      preLoaderRoute: typeof DashboardRoleChildrenRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/chat': {
      id: '/dashboard/$role/chat'
      path: '/chat'
      fullPath: '/dashboard/$role/chat'
      preLoaderRoute: typeof DashboardRoleChatRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/bookings': {
      id: '/dashboard/$role/bookings'
      path: '/bookings'
      fullPath: '/dashboard/$role/bookings'
      preLoaderRoute: typeof DashboardRoleBookingsRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/availability': {
      id: '/dashboard/$role/availability'
      path: '/availability'
      fullPath: '/dashboard/$role/availability'
      preLoaderRoute: typeof DashboardRoleAvailabilityRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/approvals': {
      id: '/dashboard/$role/approvals'
      path: '/approvals'
      fullPath: '/dashboard/$role/approvals'
      preLoaderRoute: typeof DashboardRoleApprovalsRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/dashboard/$role/achievements': {
      id: '/dashboard/$role/achievements'
      path: '/achievements'
      fullPath: '/dashboard/$role/achievements'
      preLoaderRoute: typeof DashboardRoleAchievementsRouteImport
      parentRoute: typeof DashboardRoleRoute
    }
    '/api/reports/create': {
      id: '/api/reports/create'
      path: '/api/reports/create'
      fullPath: '/api/reports/create'
      preLoaderRoute: typeof ApiReportsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/webhook': {
      id: '/api/polar/webhook'
      path: '/api/polar/webhook'
      fullPath: '/api/polar/webhook'
      preLoaderRoute: typeof ApiPolarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/checkout': {
      id: '/api/polar/checkout'
      path: '/api/polar/checkout'
      fullPath: '/api/polar/checkout'
      preLoaderRoute: typeof ApiPolarCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instapay/proof': {
      id: '/api/instapay/proof'
      path: '/api/instapay/proof'
      fullPath: '/api/instapay/proof'
      preLoaderRoute: typeof ApiInstapayProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking/lock': {
      id: '/api/booking/lock'
      path: '/api/booking/lock'
      fullPath: '/api/booking/lock'
      preLoaderRoute: typeof ApiBookingLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking/cancel': {
      id: '/api/booking/cancel'
      path: '/api/booking/cancel'
      fullPath: '/api/booking/cancel'
      preLoaderRoute: typeof ApiBookingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/transcribe': {
      id: '/api/ai/transcribe'
      path: '/api/ai/transcribe'
      fullPath: '/api/ai/transcribe'
      preLoaderRoute: typeof ApiAiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/summarize': {
      id: '/api/ai/summarize'
      path: '/api/ai/summarize'
      fullPath: '/api/ai/summarize'
      preLoaderRoute: typeof ApiAiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/intake': {
      id: '/api/ai/intake'
      path: '/api/ai/intake'
      fullPath: '/api/ai/intake'
      preLoaderRoute: typeof ApiAiIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/crisis-check': {
      id: '/api/ai/crisis-check'
      path: '/api/ai/crisis-check'
      fullPath: '/api/ai/crisis-check'
      preLoaderRoute: typeof ApiAiCrisisCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approve-therapist': {
      id: '/api/admin/approve-therapist'
      path: '/api/admin/approve-therapist'
      fullPath: '/api/admin/approve-therapist'
      preLoaderRoute: typeof ApiAdminApproveTherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role/sessions/$id': {
      id: '/dashboard/$role/sessions/$id'
      path: '/$id'
      fullPath: '/dashboard/$role/sessions/$id'
      preLoaderRoute: typeof DashboardRoleSessionsIdRouteImport
      parentRoute: typeof DashboardRoleSessionsRoute
    }
    '/api/sessions/$id/token': {
      id: '/api/sessions/$id/token'
      path: '/api/sessions/$id/token'
      fullPath: '/api/sessions/$id/token'
      preLoaderRoute: typeof ApiSessionsIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$id/end': {
      id: '/api/sessions/$id/end'
      path: '/api/sessions/$id/end'
      fullPath: '/api/sessions/$id/end'
      preLoaderRoute: typeof ApiSessionsIdEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/status': {
      id: '/api/admin/users/status'
      path: '/api/admin/users/status'
      fullPath: '/api/admin/users/status'
      preLoaderRoute: typeof ApiAdminUsersStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/instapay/verify': {
      id: '/api/admin/instapay/verify'
      path: '/api/admin/instapay/verify'
      fullPath: '/api/admin/instapay/verify'
      preLoaderRoute: typeof ApiAdminInstapayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthActionRoute: typeof AuthActionRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthRoleRoute: typeof AuthRoleRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActionRoute: AuthActionRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthRoleRoute: AuthRoleRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface TherapistsRouteChildren {
  TherapistsIdRoute: typeof TherapistsIdRoute
}

const TherapistsRouteChildren: TherapistsRouteChildren = {
  TherapistsIdRoute: TherapistsIdRoute,
}

const TherapistsRouteWithChildren = TherapistsRoute._addFileChildren(
  TherapistsRouteChildren,
)

interface DashboardRoleSessionsRouteChildren {
  DashboardRoleSessionsIdRoute: typeof DashboardRoleSessionsIdRoute
}

const DashboardRoleSessionsRouteChildren: DashboardRoleSessionsRouteChildren = {
  DashboardRoleSessionsIdRoute: DashboardRoleSessionsIdRoute,
}

const DashboardRoleSessionsRouteWithChildren =
  DashboardRoleSessionsRoute._addFileChildren(
    DashboardRoleSessionsRouteChildren,
  )

interface DashboardRoleRouteChildren {
  DashboardRoleAchievementsRoute: typeof DashboardRoleAchievementsRoute
  DashboardRoleApprovalsRoute: typeof DashboardRoleApprovalsRoute
  DashboardRoleAvailabilityRoute: typeof DashboardRoleAvailabilityRoute
  DashboardRoleBookingsRoute: typeof DashboardRoleBookingsRoute
  DashboardRoleChatRoute: typeof DashboardRoleChatRoute
  DashboardRoleChildrenRoute: typeof DashboardRoleChildrenRoute
  DashboardRoleFindRoute: typeof DashboardRoleFindRoute
  DashboardRoleInstapayRoute: typeof DashboardRoleInstapayRoute
  DashboardRoleMoodRoute: typeof DashboardRoleMoodRoute
  DashboardRoleNotificationsRoute: typeof DashboardRoleNotificationsRoute
  DashboardRolePendingRoute: typeof DashboardRolePendingRoute
  DashboardRoleProfileRoute: typeof DashboardRoleProfileRoute
  DashboardRoleReportsRoute: typeof DashboardRoleReportsRoute
  DashboardRoleSessionsRoute: typeof DashboardRoleSessionsRouteWithChildren
  DashboardRoleVibeRoute: typeof DashboardRoleVibeRoute
  DashboardRoleIndexRoute: typeof DashboardRoleIndexRoute
}

const DashboardRoleRouteChildren: DashboardRoleRouteChildren = {
  DashboardRoleAchievementsRoute: DashboardRoleAchievementsRoute,
  DashboardRoleApprovalsRoute: DashboardRoleApprovalsRoute,
  DashboardRoleAvailabilityRoute: DashboardRoleAvailabilityRoute,
  DashboardRoleBookingsRoute: DashboardRoleBookingsRoute,
  DashboardRoleChatRoute: DashboardRoleChatRoute,
  DashboardRoleChildrenRoute: DashboardRoleChildrenRoute,
  DashboardRoleFindRoute: DashboardRoleFindRoute,
  DashboardRoleInstapayRoute: DashboardRoleInstapayRoute,
  DashboardRoleMoodRoute: DashboardRoleMoodRoute,
  DashboardRoleNotificationsRoute: DashboardRoleNotificationsRoute,
  DashboardRolePendingRoute: DashboardRolePendingRoute,
  DashboardRoleProfileRoute: DashboardRoleProfileRoute,
  DashboardRoleReportsRoute: DashboardRoleReportsRoute,
  DashboardRoleSessionsRoute: DashboardRoleSessionsRouteWithChildren,
  DashboardRoleVibeRoute: DashboardRoleVibeRoute,
  DashboardRoleIndexRoute: DashboardRoleIndexRoute,
}

const DashboardRoleRouteWithChildren = DashboardRoleRoute._addFileChildren(
  DashboardRoleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R500Route: R500Route,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TherapistsRoute: TherapistsRouteWithChildren,
  BookTherapistIdRoute: BookTherapistIdRoute,
  CheckoutBookingIdRoute: CheckoutBookingIdRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  DashboardRoleRoute: DashboardRoleRouteWithChildren,
  OnboardingRoleRoute: OnboardingRoleRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  ApiAdminApproveTherapistRoute: ApiAdminApproveTherapistRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiCrisisCheckRoute: ApiAiCrisisCheckRoute,
  ApiAiIntakeRoute: ApiAiIntakeRoute,
  ApiAiSummarizeRoute: ApiAiSummarizeRoute,
  ApiAiTranscribeRoute: ApiAiTranscribeRoute,
  ApiBookingCancelRoute: ApiBookingCancelRoute,
  ApiBookingLockRoute: ApiBookingLockRoute,
  ApiInstapayProofRoute: ApiInstapayProofRoute,
  ApiPolarCheckoutRoute: ApiPolarCheckoutRoute,
  ApiPolarWebhookRoute: ApiPolarWebhookRoute,
  ApiReportsCreateRoute: ApiReportsCreateRoute,
  DashboardAdminAiLogsRoute: DashboardAdminAiLogsRoute,
  DashboardAdminAnalyticsRoute: DashboardAdminAnalyticsRoute,
  DashboardAdminContentRoute: DashboardAdminContentRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
  DashboardAdminSessionsRoute: DashboardAdminSessionsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  ApiAdminInstapayVerifyRoute: ApiAdminInstapayVerifyRoute,
  ApiAdminUsersStatusRoute: ApiAdminUsersStatusRoute,
  ApiSessionsIdEndRoute: ApiSessionsIdEndRoute,
  ApiSessionsIdTokenRoute: ApiSessionsIdTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
